# Generated by Django 4.2.8 on 2024-02-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('modified', models.DateField()),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=256)),
                ('url', models.URLField()),
            ],
        ),
    ]
